### ISSUE TITLE
Plugin does not load

### ISSUE THREAD

**Issue by admonstrator** [cryzed/Twitch-IRC-Userlist-Fix#3]
Hi there,

I installed your plugin into my HexChat 2.10.2 environment.
But if I try to enable the plugin a error message appears:
`[12:54:29]    File "<string>", line 177`
`[12:54:29]      print __module_name__, __module_version__, 'loaded successfully.'`
`[12:54:29]  ______________ ^`
`[12:54:29]  SyntaxError: invalid syntax`

Any idea whats causing this problem?

Greetings

**Comment by cryzed** [comment]
Yes, you are using the Python 3 interface while this script was written for the Python 2 interface. If you check the [forks](https://github.com/cryzed/Twitch-IRC-Userlist-Fix/network) there are two users who have ported it to Python 3 -- you can try to use these.

**Comment by admonstrator** [comment]
Thanks for the really quick answer!
The forks are working, thanks again.
